version: '3'

services:
    app:
        build: .
        container_name: django_v2
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        command: python manage.py runserver 0.0.0.0:8000
        env_file: 
            - .env.dev
        depends_on:
            - db

    db:
        image: postgres
        container_name: pgdb_v2
        volumes:
            - ./data/db:/var/lib/postgresql/data
        env_file: 
            - .env.dev

    redis:
        image: redis:alpine
        container_name: redis_v2

    celery:
        restart: always
        container_name: celery_v2
        build: .
        command: celery -A core worker -l info
        volumes:
            - ./app:/app
        env_file: 
            - .env.dev
        depends_on:
            - db
            - redis
            - app

volumes: 
    db: